### ISSUE TITLE
longitude error

### ISSUE THREAD

**Issue by mandrag0ra** [keverw/geoipfind#1]
Hi,

I don't know if you still use it, but it seems like there is an error in index.js, line 882.
`longitude: row.latitude` should be `longitude: row.longitude`, I guess.

**Comment by keverw** [comment]
Yep, looks like a copy and paste fail from the database. Fixed it, just waiting to rebuild a local copy of the database to test it. I haven't really been using this much lately but it's a easy fix :) Thank's for pointing it out

**Comment by keverw** [comment]
Updated and pushed to NPM 👍

**Comment by mandrag0ra** [comment]
Nice.. thank you.
